services:
  mader_database:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10

  mader:
    image: mader
    build: .
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - mader_database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata:
